export const WORKER_INITIATED = "worker:internal:initiated"
export const WORKER_MESSAGE = "worker:internal:message"
export const WORKER_ITERATE = "worker:internal:iterate"
export const WORKER_YIELD = "worker:internal:yield"
export const WORKER_BREAK = "worker:internal:break"
export const WORKER_TERMINATE = "worker:internal:terminate"