// File generated by scripts/pre-build.js

export const commit = "4cbcb835c0c76a5b338bf735545075090706077c";
export const commitShort = "4cbcb83";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "Initial";
export const commitAt = "2023-06-06T11:54:14.000Z";
export const secondsBetweenCommitAndBuild = 434.35;
export const minutesBetweenCommitAndBuild = 7.24;
export const timeBetweenCommitAndBuild = "7 minutes and 14 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "444.79";
export const minutesBetweenCommitAndTestCompletion = "7.41";
export const timeBetweenCommitAndTestCompletion = "7 minutes and 24 seconds";