// File generated by scripts/pre-build.js

export const commit = "6ea085b1e28c99a08e137a447f71fbc70ada9962";
export const commitShort = "6ea085b";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "1.0.0-alpha.2";
export const commitAt = "2023-06-08T00:24:07.000Z";
export const secondsBetweenCommitAndBuild = 4032.12;
export const minutesBetweenCommitAndBuild = 67.2;
export const timeBetweenCommitAndBuild = "67 minutes and 12 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "";
export const minutesBetweenCommitAndTestCompletion = "";
export const timeBetweenCommitAndTestCompletion = "";