name: release-actions
on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NO_COVERAGE_BADGE_UPDATE: 1
      PROMPT_NAME: test name
      PROMPT_EMAIL: test+email@example.com
      REDIS_URL: redis://default@localhost:6379
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DISCORD_CLIENT_ID: 1
      DISCORD_CLIENT_SECRET: 1
      DISCORD_INVITE_URL: 1
      DISCORD_REDIRECT_URL: 1
      DISCORD_BOT_TOKEN: 1
      DISCORD_BOT_PERMISSIONS: 1
      DISCORD_SERVER_ID: 1
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - run: uname -a
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          yarn install
      - run: yarn build
      # yarn coverage === c8 + yarn test
      - run: yarn coverage
      - name: Package Registry Publish - npm
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm set "registry=https://registry.npmjs.org/"
          npm set "@virtualstate:registry=https://registry.npmjs.org/"
          npm set "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}"
          npm publish --access=public
        continue-on-error: true
        env:
          YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
          NPM_TOKEN: ${{ secrets.YARN_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Package Registry Publish - GitHub
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm set "registry=https://npm.pkg.github.com/"
          npm set "@opennetwork:registry=https://npm.pkg.github.com/opennetwork"
          npm set "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}"
          npm publish --access=public
        env:
          YARN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
